apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agent.fullname" . }}
  namespace: {{ .Values.namespaces.agent }}
  labels:
    app.kubernetes.io/name: {{ include "agent.name" . }}
    helm.sh/chart: {{ include "agent.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  MIX_ENV: prod
  DOCKUP_BACKEND: {{ .Values.agent.dockupBackend }}
  DOCKUP_HOST: {{ .Values.agent.dockupHost }}
  DOCKUP_WEBSOCKET_SCHEME: {{ .Values.agent.dockupWebsocketScheme }}
  DOCKUP_HTTP_SCHEME: {{ .Values.agent.dockupHttpScheme }}
