apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.agent }}
  labels:
    app.kubernetes.io/name: {{ include "agent.name" . }}
    helm.sh/chart: {{ include "agent.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.deploys }}
  labels:
    app.kubernetes.io/name: {{ include "agent.name" . }}
    helm.sh/chart: {{ include "agent.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
