apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.pushSecretName }}
  namespace: {{ .Values.namespaces.imageBuilds }}
  labels:
    app.kubernetes.io/name: {{ include "agent.name" . }}
    helm.sh/chart: {{ include "agent.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  .dockerconfigjson: {{ template "pushServiceAccountSecret" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.pullSecretName }}
  namespace: {{ .Values.namespaces.deploys }}
  labels:
    app.kubernetes.io/name: {{ include "agent.name" . }}
    helm.sh/chart: {{ include "agent.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "pullServiceAccountSecret" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent.fullname" . }}-secrets
  labels:
    app.kubernetes.io/name: {{ include "agent.name" . }}
    helm.sh/chart: {{ include "agent.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  MIX_ENV: prod
  DOCKUP_BACKEND: {{ .Values.agent.dockupBackend }}
  DOCKUP_API_KEY: {{ .Values.agent.dockupApiKey }}
  DOCKUP_HOST: {{ .Values.agent.dockupHost }}
  DOCKUP_WEBSOCKET_SCHEME: {{ .Values.agent.dockupWebsocketScheme }}
  DOCKUP_HTTP_SCHEME: {{ .Values.agent.dockupHttpScheme }}
