apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent.fullname" . }}
  namespace: {{ .Values.namespaces.agent }}
  labels:
    app.kubernetes.io/name: {{ include "agent.name" . }}
    helm.sh/chart: {{ include "agent.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  DOCKUP_API_KEY: {{ .Values.agent.dockupApiKey | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.pushSecretName }}
  namespace: {{ .Values.namespaces.deploys }}
  labels:
    app.kubernetes.io/name: {{ include "agent.name" . }}
    helm.sh/chart: {{ include "agent.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  .dockerconfigjson: {{ template "pushServiceAccountSecret" . }}
