apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dockup.fullname" . }}
data:
  MIX_ENV: prod
  DOCKUP_WORKDIR: "/workdir"
  DOCKUP_BASE_DOMAIN: "{{ .Values.baseDomain }}"
  PGHOST: {{ .Release.Name }}-postgresql
  PGPASSWORD: {{ .Values.postgresql.postgresPassword }}
  PGUSER: {{ .Values.postgresql.postgresUser }}
  SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/token"
  GIT_HTTPS_USERNAME: {{ .Values.gitAccess.httpsUsername }}
  GIT_HTTPS_PASSWORD: {{ .Values.gitAccess.httpsPassword }}
  DOCKUP_BACKEND: helm
