apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dockup.fullname" . }}
data:
  MIX_ENV: prod
  DOCKUP_WORKDIR: "/workdir"
  DOCKUP_URL_HOST: "{{ .Values.ingress.hosts | first }}"
  DOCKUP_BASE_DOMAIN: "{{ .Values.baseDomain }}"
  PGHOST: {{ .Release.Name }}-postgresql
  PGPASSWORD: {{ .Values.postgresql.postgresPassword }}
  PGUSER: {{ .Values.postgresql.postgresUser }}
  DOCKUP_BACKEND: {{ .Values.dockupBackend }}
  DOCKUP_BITBUCKET_CLIENT_ID: "{{ .Values.bitbucket.clientId }}"
  DOCKUP_BITBUCKET_CLIENT_SECRET: "{{ .Values.bitbucket.clientSecret }}"
  DOCKUP_GOOGLE_CLIENT_ID: "{{ .Values.google.clientId }}"
  DOCKUP_GOOGLE_CLIENT_SECRET: "{{ .Values.google.clientSecret }}"
{{- if .Values.dockupSubdomainPool }}
  DOCKUP_SUBDOMAIN_POOL: "{{ .Values.dockupSubdomainPool }}"
{{- end }}
  DOCKUP_CUSTOMER_NAME: "{{ .Values.dockupCustomerName }}"
  DOCKUP_METRICS_ENDPOINT: "{{ .Values.dockupMetricsEndpoint }}"
  SENDGRID_API_KEY: "{{ .Values.sendgridApiKey }}"
  ROLLBAR_ACCESS_TOKEN: "{{ .Values.rollbarAccessToken }}"
  INTERCOM_SECRET_KEY: "{{ .Values.intercomSecretKey }}"
