apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dockup.fullname" . }}
data:
  MIX_ENV: prod
  DOCKUP_WORKDIR: "/workdir"
  DOCKUP_URL_HOST: "{{ .Values.ingress.hosts | first }}"
  DOCKUP_BASE_DOMAIN: "{{ .Values.baseDomain }}"
  PGHOST: {{ .Release.Name }}-postgresql
  PGPASSWORD: {{ .Values.postgresql.postgresPassword }}
  PGUSER: {{ .Values.postgresql.postgresUser }}
  SLACK_WEBHOOK_URL: {{ .Values.slackWebhookUrl }}
  GIT_HTTPS_USERNAME: {{ .Values.gitAccess.httpsUsername }}
  GIT_HTTPS_PASSWORD: {{ .Values.gitAccess.httpsPassword }}
  DOCKUP_BACKEND: helm
  DOCKUP_STACKDRIVER_URL: {{ .Values.stackdriverUrl }}
  DOCKUP_MAX_CONCURRENT_DEPLOYMENTS: "{{ .Values.maxConcurrentDeployments }}"
  DOCKUP_MAX_CONCURRENT_BUILDS: "{{ .Values.maxConcurrentBuilds }}"
  DOCKUP_HIBERNATE_ALL_AT: "{{ .Values.hibernateAllAt }}"
  DOCKUP_WAKEUP_ALL_AT: "{{ .Values.wakeUpAllAt }}"
  GOOGLE_CLIENT_ID: "{{ .Values.googleClientId }}"
  GOOGLE_CLIENT_SECRET: "{{ .Values.googleClientSecret }}"
  GOOGLE_CLIENT_DOMAINS: "{{ .Values.googleClientDomains }}"
