apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dockup.fullname" . }}
data:
  MIX_ENV: prod
  DOCKUP_URL_HOST: "{{ .Values.ingress.hosts | first }}"
  DOCKUP_BASE_DOMAIN: "{{ .Values.baseDomain }}"
  PGHOST: {{ .Values.cloudsql.host }}
  PGPASSWORD: {{ .Values.cloudsql.password }}
  PGUSER: {{ .Values.cloudsql.user }}
  DOCKUP_BACKEND: {{ .Values.dockupBackend }}
  DOCKUP_SUPER_ADMINS: "{{ .Values.dockupSuperAdmins }}"
  DOCKUP_GITHUB_PRIVATE_KEY_BASE64_ENCODED: "{{ .Values.github.privateKeyBase64Encoded }}"
  DOCKUP_GITHUB_APP_NAME: "{{ .Values.github.appName }}"
  DOCKUP_GITHUB_APP_ID: "{{ .Values.github.appId }}"
  DOCKUP_GOOGLE_CLIENT_ID: "{{ .Values.google.clientId }}"
  DOCKUP_GOOGLE_CLIENT_SECRET: "{{ .Values.google.clientSecret }}"
  DOCKUP_GCP_PROJECT_ID: "{{ .Values.google.gcpProjectId }}"
  DOCKUP_GCP_USER_EMAIL: "{{ .Values.google.gcpUserEmail }}"
  DOCKUP_GCB_LOGS_BUCKET: "{{ .Values.google.gcbLogsBucket }}"
  DOCKUP_CUSTOMER_NAME: "{{ .Values.dockupCustomerName }}"
  DOCKUP_METRICS_ENDPOINT: "{{ .Values.dockupMetricsEndpoint }}"
  SENDGRID_API_KEY: "{{ .Values.sendgridApiKey }}"
  ROLLBAR_ACCESS_TOKEN: "{{ .Values.rollbarAccessToken }}"
  ROLLBAR_CLIENT_KEY: "{{ .Values.rollbarClientKey }}"
  INTERCOM_SECRET_KEY: "{{ .Values.intercomSecretKey }}"
  SLACK_WEBHOOK_URL: "{{ .Values.slackWaitlistNotifications }}"
  DOCKUP_SUPPORT_SLACK_WEBHOOK_URL: "{{ .Values.slackSupportNotifications }}"
  ELIXIR_CLUSTER_COOKIE: "{{ .Values.elixirClusterCookie }}"
  DOCKUP_K8S_APP_NAME: "{{ template "dockup.name" . }}"
  DOCKUP_ANALYTICS_ENABLED: "true"
  DOCKUP_SEGMENT_WRITE_KEY: "{{ .Values.segmentWriteKey }}"
  DOCKUP_ENABLE_EMAIL_CONFIRMATION: "{{ .Values.enableEmailConfirmation }}"
  TIMBER_API_KEY: "{{ .Values.timberApiKey }}"
  DOCKUP_DEMO_ENABLED: "{{ .Values.demoEnabled }}"
