apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dockup.fullname" . }}
data:
  MIX_ENV: prod
  DOCKUP_URL_HOST: "{{ .Values.ingress.hosts | first }}"
  DOCKUP_BASE_DOMAIN: "{{ .Values.baseDomain }}"
  PGHOST: {{ .Values.cloudsql.host }}
  PGPASSWORD: {{ .Values.cloudsql.password }}
  PGUSER: {{ .Values.cloudsql.user }}
  DOCKUP_BACKEND: {{ .Values.dockupBackend }}
  DOCKUP_SUPER_ADMINS: "{{ .Values.dockupSuperAdmins }}"
  DOCKUP_BITBUCKET_CLIENT_ID: "{{ .Values.bitbucket.clientId }}"
  DOCKUP_BITBUCKET_CLIENT_SECRET: "{{ .Values.bitbucket.clientSecret }}"
  DOCKUP_GOOGLE_CLIENT_ID: "{{ .Values.google.clientId }}"
  DOCKUP_GOOGLE_CLIENT_SECRET: "{{ .Values.google.clientSecret }}"
  DOCKUP_CUSTOMER_NAME: "{{ .Values.dockupCustomerName }}"
  DOCKUP_METRICS_ENDPOINT: "{{ .Values.dockupMetricsEndpoint }}"
  SENDGRID_API_KEY: "{{ .Values.sendgridApiKey }}"
  ROLLBAR_ACCESS_TOKEN: "{{ .Values.rollbarAccessToken }}"
  INTERCOM_SECRET_KEY: "{{ .Values.intercomSecretKey }}"
  DOCKUP_GANDIV5_API_KEY: "{{ .Values.gandiv5ApiKey }}"
  SLACK_WEBHOOK_URL: "{{ .Values.slackWaitlistNotifications }}"
  ELIXIR_CLUSTER_COOKIE: "{{ .Values.elixirClusterCookie }}"
  DOCKUP_K8S_APP_NAME: "{{ template "dockup.name" . }}"
