apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dockup.fullname" . }}
data:
  MIX_ENV: prod
  DOCKUP_WORKDIR: "/workdir"
  DOCKUP_URL_HOST: "{{ .Values.ingress.hosts | first }}"
  DOCKUP_BASE_DOMAIN: "{{ .Values.baseDomain }}"
  PGHOST: {{ .Release.Name }}-postgresql
  PGPASSWORD: {{ .Values.postgresql.postgresPassword }}
  PGUSER: {{ .Values.postgresql.postgresUser }}
  SLACK_WEBHOOK_URL: {{ .Values.slackWebhookUrl }}
  DOCKUP_BACKEND: kubernetes
  DOCKUP_MAX_CONCURRENT_DEPLOYMENTS: "{{ .Values.maxConcurrentDeployments }}"
  DOCKUP_MAX_CONCURRENT_BUILDS: "{{ .Values.maxConcurrentBuilds }}"
  DOCKUP_HIBERNATE_ALL_AT: "{{ .Values.hibernateAllAt }}"
  DOCKUP_WAKEUP_ALL_AT: "{{ .Values.wakeUpAllAt }}"
  DOCKUP_SUBDOMAIN_POOL: "{{ .Values.dockupSubdomainPool }}"
  DOCKUP_CUSTOMER_NAME: "{{ .Values.dockupCustomerName }}"
  DOCKUP_METRICS_ENDPOINT: "{{ .Values.dockupMetricsEndpoint }}"
