apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "dockup.fullname" . }}
  labels:
    app: {{ template "dockup.name" . }}
    chart: {{ template "dockup.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "dockup.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "dockup.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 90  # 90 seconds for booting up
            periodSeconds: 20        # 20 seconds to probe
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 90  # 90 seconds for booting up
            periodSeconds: 20        # 20 seconds to probe
          env:
            {{- $configMapName := include "dockup.fullname" . -}}
            {{- range .Files.Lines "dot-env-file" }}
            - name: {{ . }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: {{ . }}
            {{- end }}
{{if .Values.dockupSubdomainPool}}
            - name: DOCKUP_SUBDOMAIN_POOL
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: "DOCKUP_SUBDOMAIN_POOL"
{{end}}
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
