# https://github.com/kubernetes/helm/blob/master/docs/rbac.md#helm-and-role-based-access-control
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dockup
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: dockup-kazan-to-access-cluster
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - extensions
  - apps
  - ""
  resources:
  - deployments
  - pods
  - services
  - ingresses
  - pods/log
  verbs:
  - list
  - get
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: dockup-kazan-to-access-cluster-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dockup-kazan-to-access-cluster
subjects:
- kind: ServiceAccount
  name: dockup
  namespace: {{ .Release.Namespace }}
