# https://github.com/kubernetes/helm/blob/master/docs/rbac.md#helm-and-role-based-access-control
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dockup
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: dockup-helm-to-access-tiller
  namespace: {{ .Values.helm.tillerNamespace }}
rules:
- apiGroups:
  - ""
  resources:
  - pods/portforward
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: dockup-kubectl-to-access-deploys
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - extensions
  - apps
  resources:
  - deployments
  verbs:
  - list
  - get
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: dockup-helm-to-access-tiller-binding
  namespace: {{ .Values.helm.tillerNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dockup-helm-to-access-tiller
subjects:
- kind: ServiceAccount
  name: dockup
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: dockup-kubectl-to-access-deploys-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dockup-kubectl-to-access-deploys
subjects:
- kind: ServiceAccount
  name: dockup
  namespace: {{ .Release.Namespace }}
