# Default values for dockup.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: codemancers/dockup
  tag: stable
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - ui.dockup.yourdomain.com
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

baseDomain: "dockup.yourdomain.com"

dockupBackend: "kubernetes"

maxConcurrentDeployments: 10
maxConcurrentBuilds: 10

# This url will be used to send notifications to Slack
slackWebhookUrl: "https://hooks.slack.com/services/token"

# Hibernate all successfully deployed deployments everyday
hibernateAllAt: ""              # "20:00:00" for 8pm UTC

# Wake up all hibernated deployments everyday
wakeUpAllAt: ""                 # "08:00:00" for 8am UTC

# Subdomain pool name that needs to be used for url generation
# dockupSubdomainPool: "subdomains"

bitbucket:
  clientId: "sample-client-id"
  clientSecret: "sample-client-secret"

google:
  clientId: "sample-client-id"
  clientSecret: "sample-client-secret"

dockupCustomerName: codemancers
dockupMetricsEndpoint: https://subdomainfirebaseio.com

# Namespace that dockup has to manage
dockupDeploymentsNamespace: "dockup-deployments"

# For sending emails
sendgridApiKey: "sendgrid-api-key"

# For reporting errors
rollbarAccessToken: "rollbar-access-token"

# For customer support
intercomSecretKey: "intercom-secret-key"


postgresql:
  postgresUser: user
  postgresPassword: secret
