# Default values for dockup.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: codemancers/dockup
  tag: stable
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - yourcompany.com
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

baseDomain: "company_subdomain.yourdomain.com"

dockupBackend: "kubernetes"

dockupSuperAdmins: "csv-of-admin-emails"

github:
  privateKeyBase64Encoded: "encode-pem-file-with-base64"
  appName: "dockup-app-name"
  appId: "dockup-app-id"

bitbucket:
  clientId: "sample-client-id"
  clientSecret: "sample-client-secret"

google:
  clientId: "sample-client-id"
  clientSecret: "sample-client-secret"
  gcpProjectId: "sample-project-id"
  gcpUserEmail: "sample-user-email"
  gcbLogsBucket: "sample-bucket"

dockupCustomerName: codemancers
dockupMetricsEndpoint: https://subdomainfirebaseio.com

# For sending emails
sendgridApiKey: "sendgrid-api-key"

# For reporting errors
rollbarAccessToken: "rollbar-access-token"
rollbarClientKey: "rollbar-client-key"

# For customer support
intercomSecretKey: "intercom-secret-key"

# For certs
gandiv5ApiKey: "gandiv5-api-key"

# For sending waitlist notifications to slack
slackWaitlistNotifications: "slack-waitlist-notifications"
slackSupportNotifications: "slack-support-notifications"

# For analytics
segmentWriteKey: "segment-write-key"

# For exporting logs to timber
timberApiKey: "timber-api-key"

# For connecting elixir nodes
elixirClusterCookie: "secret-cluster-cookie"

# Cloudsql instances settings
cloudsql:
  user: dockup-pg-user
  password: dockup-pg-secret
  host: dockup-pg-host
